tractusx-connector:
  enabled: true
  controlplane:
    ingresses:
      - enabled: true
        hostname: "trace-x-test-edc.dev.demo.catena-x.net"
        annotations:
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        endpoints:
          - protocol
          - management
        tls:
          enabled: true
          secretName: tls-secret
    ssi:
      miw:
        url: <path:traceability-foss/data/dev-b/edc/wallet#ssi.miw.url>
        authorityId: <path:traceability-foss/data/dev-b/edc/wallet#ssi.miw.authorityId>
      oauth:
        tokenurl: <path:traceability-foss/data/dev-b/edc/wallet#ssi.oauth.tokenurl>
        client:
          id: <path:traceability-foss/data/dev-b/edc/wallet#ssi.oauth.client.id> # sa668
          secretAlias: edc-miw-keycloak-secret-dev-b

    resources:
      limits:
        cpu: 400m
        memory: 1.5Gi
      requests:
        cpu: 200m
        memory: 1.5Gi

  dataplane:
    ingresses:
      - enabled: true
        hostname: "trace-x-test-edc-dataplane.dev.demo.catena-x.net"
        annotations:
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        endpoints:
          - public
        className: "nginx"
        tls:
          enabled: true
          secretName: tls-secret

    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 512Mi

  postgresql:
    enabled: true
    auth:
      username: "<path:traceability-foss/data/dev/edc/database#user>"
      password: "<path:traceability-foss/data/dev/edc/database#password>"
    username: "<path:traceability-foss/data/dev/edc/database#user>"
    password: "<path:traceability-foss/data/dev/edc/database#password>"
    jdbcUrl: "jdbc:postgresql://tracex-test-edc-provider-edc-postgresql-hl:5432/edc"

  backendService:
    httpProxyTokenReceiverUrl: "https://traceability-test.dev.demo.catena-x.net/api/callback/endpoint-data-reference"

  vault:
    secretNames:
      transferProxyTokenSignerPrivateKey: token-signer-cert-key-dev
      transferProxyTokenSignerPublicKey: token-signer-cert-dev
      transferProxyTokenEncryptionAesKey: token-signer-aes-key

edc-postgresql:
  enabled: true
  auth:
    database: edc
    username: <path:traceability-foss/data/dev/edc/database#user>
    postgresPassword: <path:traceability-foss/data/dev/edc/database#password>
    password: <path:traceability-foss/data/dev/edc/database#password>
