tractusx-connector:
  controlplane:
    ingresses:
      - enabled: true
        hostname: "trace-x-edc.dev.demo.catena-x.net"
  dataplane:
    ingresses:
      - enabled: true
        hostname: "trace-x-edc-dataplane.dev.demo.catena-x.net"

  backendService:
    httpProxyTokenReceiverUrl: "https://traceability.dev.demo.catena-x.net/api/callback/endpoint-data-reference"

  vault:
    secretNames:
      transferProxyTokenSignerPrivateKey: token-signer-cert-key-dev
      transferProxyTokenSignerPublicKey: token-signer-cert-dev
      transferProxyTokenEncryptionAesKey: token-signer-aes-key

edc-postgresql:
  enabled: true
