tractusx-connector:
  install:
    postgresql: false
    daps: false
    vault: false
  participant:
    id: BPNL00000003CML1

  controlplane:
    ingresses:
      - enabled: true
        hostname: "trace-x-edc-e2e-a.dev.demo.catena-x.net"
        annotations:
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        endpoints:
          - protocol
          - management
        tls:
          enabled: true
          secretName: tls-secret

  dataplane:
    ingresses:
      - enabled: true
        hostname: "trace-x-edc-e2e-a-dataplane.dev.demo.catena-x.net"
        annotations:
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        endpoints:
          - public
        className: "nginx"
        tls:
          enabled: true
          secretName: tls-secret

  ## currently we need to provide a url but is not used anywhere
  backendService:
    httpProxyTokenReceiverUrl: "https://tracex-submodel-server.dev.demo.catena-x.net/data/endpoint-data-reference-provider1"

  vault:
    secretNames:
      transferProxyTokenSignerPrivateKey: token-signer-cert-key-dev
      transferProxyTokenSignerPublicKey: token-signer-cert-dev
      transferProxyTokenEncryptionAesKey: token-signer-aes-key
      dapsPrivateKey: daps-cert-edc-e2e-a-provider-private
      dapsPublicKey: daps-cert-edc-e2e-a-provider-public

  daps:
    url: "https://daps1.int.demo.catena-x.net"
    clientId: FC:5B:90:F1:9E:6B:1C:09:39:83:19:9A:3E:0D:1D:DB:B9:1A:61:45:keyid:FC:5B:90:F1:9E:6B:1C:09:39:83:19:9A:3E:0D:1D:DB:B9:1A:61:45

edc-postgresql:
  enabled: true
  auth:
    database: edc
    username: <path:traceability-foss/data/dev/edc/database#user>
    postgresPassword: <path:traceability-foss/data/dev/edc/database#password>
    password: <path:traceability-foss/data/dev/edc/database#password>
