tractusx-connector:
  controlplane:
    ingresses:
      - enabled: true
        hostname: "trace-x-edc-e2e-b.dev.demo.catena-x.net"

  dataplane:
    ingresses:
      - enabled: true
        hostname: "trace-x-edc-e2e-b-dataplane.dev.demo.catena-x.net"

  ## currently we need to provide a url but is not used anywhere
  backendService:
    httpProxyTokenReceiverUrl: "https://traceability-e2e-b.dev.demo.catena-x.net/api/callback/endpoint-data-reference"

  vault:
    secretNames:
      transferProxyTokenSignerPrivateKey: token-signer-cert-key-dev
      transferProxyTokenSignerPublicKey: token-signer-cert-dev
      transferProxyTokenEncryptionAesKey: token-signer-aes-key

edc-postgresql:
  enabled: true
