tractusx-connector:
  enabled: true
  controlplane:
    ingresses:
      - enabled: true
        hostname: "trace-x-edc.dev.demo.catena-x.net"
  dataplane:
    ingresses:
      - enabled: true
        hostname: "trace-x-edc-dataplane.dev.demo.catena-x.net"

  backendService:
    httpProxyTokenReceiverUrl: "https://traceability.dev.demo.catena-x.net/api/callback/endpoint-data-reference"
  postgresql:
    enabled: true
    auth:
      username: "<path:traceability-foss/data/dev/edc/database#user>"
      password: "<path:traceability-foss/data/dev/edc/database#password>"
    username: "<path:traceability-foss/data/dev/edc/database#user>"
    password: "<path:traceability-foss/data/dev/edc/database#password>"
    jdbcUrl: "jdbc:postgresql://tracex-edc-provider-edc-postgresql-hl:5432/edc"
  vault:
    secretNames:
      transferProxyTokenSignerPrivateKey: token-signer-cert-key-dev
      transferProxyTokenSignerPublicKey: token-signer-cert-dev
      transferProxyTokenEncryptionAesKey: token-signer-aes-key

edc-postgresql:
  enabled: true
  auth:
    database: edc
    username: <path:traceability-foss/data/dev/edc/database#user>
    postgresPassword: <path:traceability-foss/data/dev/edc/database#password>
    password: <path:traceability-foss/data/dev/edc/database#password>
