tractusx-connector:
  install:
    postgresql: false
    daps: false
    vault: false
  participant:
    id: BPNL00000003CML1

  controlplane:
    ingresses:
      - enabled: true
        hostname: "trace-x-edc-test.dev.demo.catena-x.net"
        annotations:
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        endpoints:
          - protocol
          - management
        tls:
          enabled: true
          secretName: tls-secret

  dataplane:
    ingresses:
      - enabled: true
        hostname: "trace-x-edc-test-dataplane.dev.demo.catena-x.net"
        annotations:
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        endpoints:
          - public
        className: "nginx"
        tls:
          enabled: true
          secretName: tls-secret

  ## currently we need to provide a url but is not used anywhere
  backendService:
    httpProxyTokenReceiverUrl: "https://tracex-submodel-server.dev.demo.catena-x.net/data/endpoint-data-reference-provider1"

  vault:
    secretNames:
      transferProxyTokenSignerPrivateKey: token-signer-cert-key-dev
      transferProxyTokenSignerPublicKey: token-signer-cert-dev
      transferProxyTokenEncryptionAesKey: token-signer-aes-key
      dapsPrivateKey: daps-cert-edc-test-provider-private
      dapsPublicKey: daps-cert-edc-test-provider-public

  daps:
    url: "https://daps1.int.demo.catena-x.net"
    clientId: 35:CA:B1:DD:B2:1C:0B:4F:87:CE:CD:6D:18:F4:E7:66:7D:1B:85:10:keyid:35:CA:B1:DD:B2:1C:0B:4F:87:CE:CD:6D:18:F4:E7:66:7D:1B:85:10

edc-postgresql:
  enabled: true
  auth:
    database: edc
    username: <path:traceability-foss/data/dev/edc/database#user>
    postgresPassword: <path:traceability-foss/data/dev/edc/database#password>
    password: <path:traceability-foss/data/dev/edc/database#password>
