name: "[BE] Load Test"

on:
  workflow_dispatch:
    inputs:
      technical_api_key:
        description: Trace-X Technical API Key
        required: true
      simulation-class:
        type: choice
        description: 'Select the simulation class to run'
        required: true
        default: 'simulation.SynchonizationSimulation'
        options:
          - 'simulation.SynchonizationSimulation'
          - 'simulation.NotificationSimulation'
          - 'simulation.DashboardSimulation'
      base-url:
        type: choice
        description: 'Select the base url of the target environment'
        required: true
        default: 'https://traceability-foss-a.integration.cofinity-x.com/api'
        options:
          - 'https://traceability-foss-a.integration.cofinity-x.com/api'
          - 'https://traceability-foss-b.integration.cofinity-x.com/api'

env:
  JAVA_VERSION: 17

jobs:
  load-test:
    runs-on: [ self-hosted, linux ]
    container:
      image: maven:3-eclipse-temurin-21
    steps:
      - name: Install jq
        run: |
          apt update
          apt install jq -y

      - name: Mask token
        run: |
          TECHNICAL_API_KEY=$(jq -r '.inputs.technical_api_key' $GITHUB_EVENT_PATH)
          echo ::add-mask::$TECHNICAL_API_KEY
          echo TECHNICAL_API_KEY=$TECHNICAL_API_KEY >> $GITHUB_ENV

      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Gatling tests
        env:
          TECHNICAL_API_KEY: ${{ env.TECHNICAL_API_KEY }}
          BASE_URL: ${{ github.event.inputs.base-url }}
        run: |
          mvn gatling:test -pl tx-gatling-tests -Dgatling.simulationClass=${{ github.event.inputs.simulation-class }}

      - name: Upload results
        uses: actions/upload-artifact@master
        with:
          name: gatling-results
          path: tx-gatling-tests/target/gatling/
